version: '3.7'
services:
  ##############
  ## POSTGRES ##
  postgres_db:
    image: postgres
    networks:
      - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=english_assistant
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./server/database/data/dev:/var/lib/postgresql/data
    container_name: postgres_db
  ##############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - webapp
      - database
    ports:
      - 3000:3000
    volumes:
      - ./server/node_modules:/app/node_modules
      - ./server/src:/app/src
    depends_on:
      - postgres_db
    restart: always
    container_name: server
networks:
  webapp:
    driver: bridge
  database:
    driver: bridge